---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Add Docker apt key.
  ansible.builtin.apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    filename: docker
    update_cache: true

- name: Install Docker and Docker-compose
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: latest
    update_cache: true
  notify: restart docker