---
# ansible-playbook playbooks/pl_zbx_docker_setup_agent_local.yml -bK

- name: Zabbix Agent (local)
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    zabbix_version: '7.4.5'
    zabbix_image_flavor: 'alpine'
    zabbix_deployment_mode: 'agent'

    # Agent connects to a reachable Server or Proxy address (IP/FQDN)
    zbx_agent_server_host: 'zabbix-server'
    zbx_agent_hostname: 'agent-hostname'

    # API (optional)
    zabbix_host_groups:
      - "Linux servers"
    zabbix_link_templates:
      - "Linux by Zabbix agent"

  tasks:
    - name: Install Docker prerequisites
      ansible.builtin.include_role:
        name: install_docker
      vars:
        docker_users:
          - administrator
          - zabbix
      when: ansible_os_family != 'Windows'

    - name: Deploy Zabbix stack (agent only)
      ansible.builtin.include_role:
        name: install_zabbix_docker
      vars:
        zbx_container_state: 'present'
      when: ansible_os_family != 'Windows'
